observation_sources: visionscan
visionscan:
  sensor_frame: camera_link
  data_type: LaserScan
  topic: /vision/scan
  marking: true
  clearing: true

footprint: [[-0.18, -0.14], [-0.18, 0.14], [0.18, 0.14], [0.18, -0.14]]
inflation_radius: 0.5
cost_scaling_factor: 10.0
