DWAPlannerROS:
  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  max_vel_x: 0.6
  min_vel_x: 0.0
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false
  sim_time: 2.0
  vx_samples: 10
  vtheta_samples: 20
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.5
  stop_time_buffer: 0.2
  prune_plan: true

  # ↓↓↓ 시각화 토픽 출력 활성화 ↓↓↓
  publish_traj_pc: true
  publish_cost_grid_pc: true
